#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Check_MK Check SSL Issuer
#
# Copyright 2023, Marco Malavolti <marco.malavolti[at]garr.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

def check_ssl_issuer_desc(params):
    if params.get("description"):
        return "%s" % params["description"]
    return "Check SSL Issuer"

def check_ssl_issuer_arguments(params):

    args = ""

    if "hostname" in params:
        args += "--hostname %s" % quote_shell_string(params["hostname"])
    else:
        args += "--hostname mdx.idem.garr.it"

    if "issuer" in params:
        args += "--issuer %s" % quote_shell_string(params["issuer"])
    else:
        args += "--issuer GEANT OV RSA CA 4"

    return args

active_check_info['ssl_issuer'] = {
    "command_line"        : '$USER2$/check_ssl_issuer.py',
    "argument_function"   : check_ssl_issuer_arguments,
    "service_description" : check_ssl_issuer_desc,
    "has_perfdata"        : True,
}
